name: Editor Demo  # ci文件的名字
env:
 CI: false
# 控制工作流程何时运行
on:
 push:
  branches: [ main ]
permissions:
 contents: write
# CI/CD通过执行一个个的Job来完成每个阶段的工作，这里配置每个Jobs
jobs:
 # Job的名称
 Check:
  # Runner，github托管的虚拟机环境，用来执行下面的Job命令
  runs-on: ubuntu-latest
  steps:
  # 子步骤名称
  - name: checkout
    uses: actions/checkout@v3
    with:
      node-version: '16'

 Deploy:
   needs: Check
   # The type of runner that the job will run on
   runs-on: ubuntu-latest

   # Steps represent a sequence of tasks that will be executed as part of the job
   steps:
     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
     - name: checkout
       uses: actions/checkout@v3
       with:
         node-version: '16'

     # Runs a single command using the runners shell
     - name: build
       uses: actions/setup-node@v3
       with:
         node-version: '16'
       env:
         ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
         BRANCH: main
     - run: yarn
     - run: yarn build

     - name: deploy
       uses: JamesIves/github-pages-deploy-action@v4.3.3
       with:
         branch: gh-pages
         folder: dist