name: Editor Demo  # ci文件的名字
env:
 CI: false
# 控制工作流程何时运行
on:
 push:
  branches: [ main ]
permissions:
 contents: write
# CI/CD通过执行一个个的Job来完成每个阶段的工作，这里配置每个Jobs
jobs:
 # Job的名称
 Check:
  # Runner，github托管的虚拟机环境，用来执行下面的Job命令
  runs-on: ubuntu-latest
  steps:
  # 子步骤名称
  - name: checkout
    uses: actions/checkout@v3
    with:
      persist-credentials: false

 Deploy:
   needs: Check # 依赖步骤
   runs-on: ubuntu-latest

   # Steps represent a sequence of tasks that will be executed as part of the job
   steps:
     - name: Install pnpm # 安装pnpm
       uses: pnpm/action-setup@v2
       with:
         version: 6.0.2

     - name: Install and Build # 下载依赖 打包项目
       run: |
         pnpm install
         pnpm run build

     - name: Deploy # 将打包内容发布到 github page
       uses: JamesIves/github-pages-deploy-action@v4 # 使用别人写好的actions
       with: # 自定义环境变量
         branch: gh-pages # github pages 指定分支
         folder: dist # build后生成的目录
         clean: true